### ISSUE TITLE
Error when opening xplr with xpm installed

### ISSUE THREAD

**Issue by scalarwaves** [dtomvan/xpm.xplr#6]
`[2022-10-23 22:45:57.751360113 -04:00] ERROR   runtime error: $HOME/.local/share/xplr/dtomvan/xpm.xplr/xpm/lib.lua:51: attempt to index local 'mod' (a boolean value)
stack traceback:
	[C]: in function '__index'
	$HOME/.local/share/xplr/dtomvan/xpm.xplr/xpm/lib.lua:51: in function 'config'
	$HOME/.local/share/xplr/dtomvan/xpm.xplr/xpm/lib.lua:56: in function 'use_plugin'
	$HOME/.local/share/xplr/dtomvan/xpm.xplr/xpm.lua:117: in function 'install_plugins'
	$HOME/.local/share/xplr/dtomvan/xpm.xplr/xpm.lua:25: in function <$HOME/.local/share/xplr/dtomvan/xpm.xplr/xpm.lua:9>
	[string "init"]:2662: in main chunk`

I will experiment with uninstalling plugins and trying again to see if it's reproducible.

Thanks!

**Comment by scalarwaves** [comment]
This seems to be the offending code block:

```lua
  if status then
    local config = plugin.setup
    if type(config) ~= "function" then
      config = function()
        local ok, mod = pcall(require, util.plug_modname(name))
        if ok then
          pcall(mod.setup)
        end
      end
    end

    config()

    local after = plugin.after
    if type(after) == "function" then
      after()
    end

    return true
  end
end
```

**Comment by scalarwaves** [comment]
So I fixed it by removing everything from the .local/share/xplr folder and loading xplr again. It reinstalled all the plugins and this error vanished,though now I have an error about icon.lua not being found but I'll address that in the correct repo.

**Comment by dtomvan** [comment]
Sorry for not responding, I'll look into it

**Comment by dtomvan** [comment]
Also, could you show the relevant part of your init.lua?

**Comment by scalarwaves** [comment]
No worries. I tried the xplr config again from scratch and read the READMEs for each plugin more carefully, now I get no errors.
